# Generated by Django 3.0.2 on 2020-01-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('boardNum', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=100)),
                ('recommend', models.IntegerField(default=0)),
                ('unrecommend', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('category', models.CharField(max_length=10)),
                ('Field', models.IntegerField(default=0)),
            ],
        ),
    ]
