# Generated by Django 3.0.3 on 2020-02-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boardNum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
