# Generated by Django 3.0.2 on 2020-01-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200130_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='whatboard',
            field=models.IntegerField(default=1),
        ),
    ]
