# Generated by Django 3.0.2 on 2020-01-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_whatboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='whatboard',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
