# Generated by Django 3.0.2 on 2020-02-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=10)),
            ],
        ),
    ]
