# Generated by Django 3.0.2 on 2020-02-04 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, '패스워드는 5글자 이상 15자 이하여야 합니다.')]),
        ),
    ]
