# Generated by Django 3.0.2 on 2020-02-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
